### ISSUE TITLE
Your indentation looks to be a little off from Ruby Best paractices.

### ISSUE THREAD

**Issue by DouglasAllen** [AlessandroMinali/qbudget#1]
HeY! Got your video from YouTube and went after the code. I could fork it and send you a pull request after I put your code files through vim or gvim but you can do that too. 
Try it. esc shitfV shiftG = then save shift: w q You'll like it. Then you can try to get your editer set up for this style. One pet peve of mine is screencasts with black backgrounds. yuck! Try something at least like Josh Cheeks of Ruby-Kickstart. Have fun. I just hope that we can get you awesome for the Ruby Comm....

**Comment by AlessandroMinali** [comment]
Yea my IDE sometimes destroys the double spaced indentation's...I'd accept the pull if it purely cosmetic :) Cheers
